package com.google.android.gms.games.internal.player;

import android.text.TextUtils;

public final class zzd {
    public final String name;
    public final String zzcd;
    public final String zzci;
    public final String zzmc;
    public final String zzmd;
    public final String zzme;
    public final String zzmf;
    public final String zzmg;
    public final String zzmh;
    public final String zzmi;
    public final String zzmj;
    public final String zzmk;
    public final String zzml;
    public final String zzmm;
    public final String zzmn;
    public final String zzmo;
    public final String zzmp;
    public final String zzmq;
    public final String zzmr;
    private final String zzms;
    public final String zzmt;
    public final String zzmu;
    public final String zzmv;
    public final String zzmw;
    public final String zzmx;
    public final String zzmy;
    public final String zzmz;
    public final String zzna;
    public final String zznb;
    public final String zznc;
    public final String zznd;
    public final String zzne;
    public final String zznf;
    public final String zzng;
    public final String zznh;
    public final String zzni;

    public zzd(String str) {
        String str2;
        String str3 = "next_level";
        String str4 = "current_level_max_xp";
        String str5 = "current_level_min_xp";
        String str6 = "current_level";
        String str7 = "current_xp_total";
        String str8 = "played_with_timestamp";
        String str9 = "is_in_circles";
        String str10 = "last_updated";
        String str11 = "profile_hi_res_image_url";
        String str12 = "profile_hi_res_image_uri";
        String str13 = "profile_icon_image_url";
        String str14 = "profile_icon_image_uri";
        String str15 = "profile_name";
        String str16 = "next_level_max_xp";
        String str17 = "external_player_id";
        if (TextUtils.isEmpty(str)) {
            this.zzmc = str17;
            this.zzmd = str15;
            this.zzme = str14;
            this.zzmf = str13;
            this.zzmg = str12;
            this.zzmh = str11;
            this.zzmi = str10;
            this.zzmj = str9;
            this.zzmk = str8;
            this.zzml = str7;
            this.zzmm = str6;
            this.zzmn = str5;
            this.zzmo = str4;
            this.zzmp = str3;
            this.zzmq = str16;
            this.zzmr = "last_level_up_timestamp";
            this.zzcd = "player_title";
            this.zzms = "has_all_public_acls";
            this.zzmt = "is_profile_visible";
            this.zzmu = "most_recent_external_game_id";
            this.zzmv = "most_recent_game_name";
            this.zzmw = "most_recent_activity_timestamp";
            this.zzmx = "most_recent_game_icon_uri";
            this.zzmy = "most_recent_game_hi_res_uri";
            this.zzmz = "most_recent_game_featured_uri";
            this.zzna = "has_debug_access";
            this.zzci = "gamer_tag";
            this.name = "real_name";
            this.zznb = "banner_image_landscape_uri";
            this.zznc = "banner_image_landscape_url";
            this.zznd = "banner_image_portrait_uri";
            this.zzne = "banner_image_portrait_url";
            this.zznf = "gamer_friend_status";
            this.zzng = "gamer_friend_update_timestamp";
            this.zznh = "is_muted";
            str2 = "total_unlocked_achievements";
        } else {
            String valueOf = String.valueOf(str);
            this.zzmc = str17.length() != 0 ? valueOf.concat(str17) : new String(valueOf);
            String valueOf2 = String.valueOf(str);
            this.zzmd = str15.length() != 0 ? valueOf2.concat(str15) : new String(valueOf2);
            String valueOf3 = String.valueOf(str);
            this.zzme = str14.length() != 0 ? valueOf3.concat(str14) : new String(valueOf3);
            String valueOf4 = String.valueOf(str);
            this.zzmf = str13.length() != 0 ? valueOf4.concat(str13) : new String(valueOf4);
            String valueOf5 = String.valueOf(str);
            this.zzmg = str12.length() != 0 ? valueOf5.concat(str12) : new String(valueOf5);
            String valueOf6 = String.valueOf(str);
            this.zzmh = str11.length() != 0 ? valueOf6.concat(str11) : new String(valueOf6);
            String valueOf7 = String.valueOf(str);
            this.zzmi = str10.length() != 0 ? valueOf7.concat(str10) : new String(valueOf7);
            String valueOf8 = String.valueOf(str);
            this.zzmj = str9.length() != 0 ? valueOf8.concat(str9) : new String(valueOf8);
            String valueOf9 = String.valueOf(str);
            this.zzmk = str8.length() != 0 ? valueOf9.concat(str8) : new String(valueOf9);
            String valueOf10 = String.valueOf(str);
            this.zzml = str7.length() != 0 ? valueOf10.concat(str7) : new String(valueOf10);
            String valueOf11 = String.valueOf(str);
            this.zzmm = str6.length() != 0 ? valueOf11.concat(str6) : new String(valueOf11);
            String valueOf12 = String.valueOf(str);
            this.zzmn = str5.length() != 0 ? valueOf12.concat(str5) : new String(valueOf12);
            String valueOf13 = String.valueOf(str);
            this.zzmo = str4.length() != 0 ? valueOf13.concat(str4) : new String(valueOf13);
            String valueOf14 = String.valueOf(str);
            this.zzmp = str3.length() != 0 ? valueOf14.concat(str3) : new String(valueOf14);
            String valueOf15 = String.valueOf(str);
            this.zzmq = str16.length() != 0 ? valueOf15.concat(str16) : new String(valueOf15);
            String valueOf16 = String.valueOf(str);
            String str18 = "last_level_up_timestamp";
            this.zzmr = str18.length() != 0 ? valueOf16.concat(str18) : new String(valueOf16);
            String valueOf17 = String.valueOf(str);
            String str19 = "player_title";
            this.zzcd = str19.length() != 0 ? valueOf17.concat(str19) : new String(valueOf17);
            String valueOf18 = String.valueOf(str);
            String str20 = "has_all_public_acls";
            this.zzms = str20.length() != 0 ? valueOf18.concat(str20) : new String(valueOf18);
            String valueOf19 = String.valueOf(str);
            String str21 = "is_profile_visible";
            this.zzmt = str21.length() != 0 ? valueOf19.concat(str21) : new String(valueOf19);
            String valueOf20 = String.valueOf(str);
            String str22 = "most_recent_external_game_id";
            this.zzmu = str22.length() != 0 ? valueOf20.concat(str22) : new String(valueOf20);
            String valueOf21 = String.valueOf(str);
            String str23 = "most_recent_game_name";
            this.zzmv = str23.length() != 0 ? valueOf21.concat(str23) : new String(valueOf21);
            String valueOf22 = String.valueOf(str);
            String str24 = "most_recent_activity_timestamp";
            this.zzmw = str24.length() != 0 ? valueOf22.concat(str24) : new String(valueOf22);
            String valueOf23 = String.valueOf(str);
            String str25 = "most_recent_game_icon_uri";
            this.zzmx = str25.length() != 0 ? valueOf23.concat(str25) : new String(valueOf23);
            String valueOf24 = String.valueOf(str);
            String str26 = "most_recent_game_hi_res_uri";
            this.zzmy = str26.length() != 0 ? valueOf24.concat(str26) : new String(valueOf24);
            String valueOf25 = String.valueOf(str);
            String str27 = "most_recent_game_featured_uri";
            this.zzmz = str27.length() != 0 ? valueOf25.concat(str27) : new String(valueOf25);
            String valueOf26 = String.valueOf(str);
            String str28 = "has_debug_access";
            this.zzna = str28.length() != 0 ? valueOf26.concat(str28) : new String(valueOf26);
            String valueOf27 = String.valueOf(str);
            String str29 = "gamer_tag";
            this.zzci = str29.length() != 0 ? valueOf27.concat(str29) : new String(valueOf27);
            String valueOf28 = String.valueOf(str);
            String str30 = "real_name";
            this.name = str30.length() != 0 ? valueOf28.concat(str30) : new String(valueOf28);
            String valueOf29 = String.valueOf(str);
            String str31 = "banner_image_landscape_uri";
            this.zznb = str31.length() != 0 ? valueOf29.concat(str31) : new String(valueOf29);
            String valueOf30 = String.valueOf(str);
            String str32 = "banner_image_landscape_url";
            this.zznc = str32.length() != 0 ? valueOf30.concat(str32) : new String(valueOf30);
            String valueOf31 = String.valueOf(str);
            String str33 = "banner_image_portrait_uri";
            this.zznd = str33.length() != 0 ? valueOf31.concat(str33) : new String(valueOf31);
            String valueOf32 = String.valueOf(str);
            String str34 = "banner_image_portrait_url";
            this.zzne = str34.length() != 0 ? valueOf32.concat(str34) : new String(valueOf32);
            String valueOf33 = String.valueOf(str);
            String str35 = "gamer_friend_status";
            this.zznf = str35.length() != 0 ? valueOf33.concat(str35) : new String(valueOf33);
            String valueOf34 = String.valueOf(str);
            String str36 = "gamer_friend_update_timestamp";
            this.zzng = str36.length() != 0 ? valueOf34.concat(str36) : new String(valueOf34);
            String valueOf35 = String.valueOf(str);
            String str37 = "is_muted";
            this.zznh = str37.length() != 0 ? valueOf35.concat(str37) : new String(valueOf35);
            String valueOf36 = String.valueOf(str);
            String str38 = "total_unlocked_achievements";
            str2 = str38.length() != 0 ? valueOf36.concat(str38) : new String(valueOf36);
        }
        this.zzni = str2;
    }
}
